### ISSUE TITLE
react-native-payments doesn't build with Xcode 12.5

### ISSUE THREAD

**Issue by A-Yatsyk** [naoufal/react-native-payments#297]
### 🐛 Bug Report

react-native-payments in a React Native project fails to build with the following error:
`{MY_PROJECT}/ios/Pods/Stripe/Stripe/STPPinManagementService.m:51:81: 'new' is unavailable: You cannot directly instantiate an STPIssuingCardPin`
`{MY_PROJECT}/ios/Pods/Stripe/Stripe/STPPinManagementService.m:101:81: 'new' is unavailable: You cannot directly instantiate an STPIssuingCardPin`

**Build log**

> In file included from {MY_PROJECT}/ios/Pods/Stripe/Stripe/STPPinManagementService.m:11:
{MY_PROJECT}/ios/Pods/Stripe/Stripe/PublicHeaders/STPIssuingCardPin.h:22:1: note: 'init' has been explicitly marked unavailable here
 (instancetype)init __attribute__((unavailable("You cannot directly instantiate an STPIssuingCardPin")));
^
{MY_PROJECT}/ios/Pods/Stripe/Stripe/STPPinManagementService.m:101:81: error: 'new' is unavailable: You cannot directly instantiate an STPIssuingCardPin 

> In file included from {MY_PROJECT}/ios/Pods/Stripe/Stripe/STPPinManagementService.m:11:
{MY_PROJECT}/ios/Pods/Stripe/Stripe/PublicHeaders/STPIssuingCardPin.h:22:1: note: 'init' has been explicitly marked unavailable here
 (instancetype)init __attribute__((unavailable("You cannot directly instantiate an STPIssuingCardPin")));
 
Cleaning the Xcode build folder didn't help, nor does updating react-native-payments to the latest versions

**To Reproduce**

1. Install Xcode 12.5 from Apple
2. Open a React Native project with react-native-payments
3. Try to build that project
4. The build fails

**Environment**

- Xcode 12.5
- iOS: 14.4
- macOS 11.2.3
- React Native 0.63.3
- React Native Payments 0.8.3
- React 16.13.1
- Pods: 
    - Stripe (19.4.0)
    - Braintree (4.37.1)

**Comment by mouessam** [comment]
I have the same issue i think this is du to the version of the Strip Library used 19.4.0, I have checked the stripe repo and found the release 19.4.1 for fixing this issue, but i falled to fix it sorry not experienced in ios, i don't know of any of these can help you

**Comment by muhammadahsaniqbal** [comment]
Facing same issue, anxiously awaiting the fix.

**Comment by Moistbobo** [comment]
Xcode 12.5 introduces a few challenges to react native. Downgrading is not an option if you are developing for release, doing so will just set yourself up for a footgun.

That being said, I was able to resolve all build issues by doing the following:

1. In `ios/Podfile`, check that `platform :ios, '11.0'`

2. You will need to change the ios deployment target to match the podfile version. This can be done under `Project > Info tab > Deployment target`

3. In `Project > Build Settings > Library Search Paths`, replace the line `"$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)"` with `"$(TOOLCHAIN_DIR)/usr/lib/swift-5.4/$(PLATFORM_NAME)"`

4. If you encounter something along the lines of `undefined symbol libswiftWebKit.tbd`, 
Add libswiftWebKit.tbd by `Project > [Your Project Target] > Build Phases > Link binary With Libraries > add libswiftWebKit.tbd as a linked library`

**Comment by nurjs** [comment]
the same issue, pls help

**Comment by michbil** [comment]
Apparently library need to migrate from stripe api 19 to 21. I have made some experiments, but test with real cards needed.

I have added 21.3.1 to main project Podfile,
```
 pod 'Stripe', '21.3.1'
 ```
Also raised platform to iOS 11
```
platform :ios, '11.0'
```

And patched GatewayManager.m . Since version 21 is written in swift, Stripe need to be imported as a framework now. I still have no idea how to replace -#if __has_include(<Stripe/Stripe.h>) blocks, so I have commented them for now. Also had to resolve lot of SWIFT-related problems on the project. This way I have build my application successfully, but not yet tested with real cards. 

Downside of this solution is that minimum target is iOS 11 now, so can be not suitable for somebody.

```
diff --git a/node_modules/react-native-payments/ios/GatewayManager.m b/node_modules/react-native-payments/ios/GatewayManager.m
index d23c4ae..a09e9f3 100644
--- a/node_modules/react-native-payments/ios/GatewayManager.m
+++ b/node_modules/react-native-payments/ios/GatewayManager.m
@@ -1,8 +1,7 @@
 #import "GatewayManager.h"
 
-#if __has_include(<Stripe/Stripe.h>)
-#import <Stripe/Stripe.h>
-#endif
+@import Stripe;
+
 
 #if __has_include(<BraintreeApplePay/BraintreeApplePay.h>)
 #import <BraintreeApplePay/BraintreeApplePay.h>
@@ -14,9 +13,7 @@ + (NSArray *)getSupportedGateways
 {
     NSMutableArray *supportedGateways = [NSMutableArray array];
 
-#if __has_include(<Stripe/Stripe.h>)
     [supportedGateways addObject:@"stripe"];
-#endif
 
 #if __has_include(<BraintreeApplePay/BraintreeApplePay.h>)
     [supportedGateways addObject:@"braintree"];
@@ -28,11 +25,11 @@ + (NSArray *)getSupportedGateways
 - (void)configureGateway:(NSDictionary *_Nonnull)gatewayParameters
       merchantIdentifier:(NSString *_Nonnull)merchantId
 {
-#if __has_include(<Stripe/Stripe.h>)
+
     if ([gatewayParameters[@"gateway"] isEqualToString:@"stripe"]) {
         [self configureStripeGateway:gatewayParameters merchantIdentifier:merchantId];
     }
-#endif
+
 
 #if __has_include(<BraintreeApplePay/BraintreeApplePay.h>)
     if ([gatewayParameters[@"gateway"] isEqualToString:@"braintree"]) {
@@ -44,9 +41,9 @@ - (void)configureGateway:(NSDictionary *_Nonnull)gatewayParameters
 - (void)createTokenWithPayment:(PKPayment *_Nonnull)payment
                     completion:(void (^_Nullable)(NSString * _Nullable token, NSError * _Nullable error))completion
 {
-#if __has_include(<Stripe/Stripe.h>)
+
     [self createStripeTokenWithPayment:payment completion:completion];
-#endif
+
 
 #if __has_include(<BraintreeApplePay/BraintreeApplePay.h>)
     [self createBraintreeTokenWithPayment:payment completion:completion];
@@ -57,16 +54,15 @@ - (void)createTokenWithPayment:(PKPayment *_Nonnull)payment
 - (void)configureStripeGateway:(NSDictionary *_Nonnull)gatewayParameters
             merchantIdentifier:(NSString *_Nonnull)merchantId
 {
-#if __has_include(<Stripe/Stripe.h>)
+
     NSString *stripePublishableKey = gatewayParameters[@"stripe:publishableKey"];
     [[STPPaymentConfiguration sharedConfiguration] setPublishableKey:stripePublishableKey];
     [[STPPaymentConfiguration sharedConfiguration] setAppleMerchantIdentifier:merchantId];
-#endif
+
 }
 
 - (void)createStripeTokenWithPayment:(PKPayment *)payment completion:(void (^)(NSString * _Nullable, NSError * _Nullable))completion
 {
-#if __has_include(<Stripe/Stripe.h>)
     [[STPAPIClient sharedClient] createTokenWithPayment:payment completion:^(STPToken * _Nullable token, NSError * _Nullable error)
     {
         if (error) {
@@ -75,7 +71,6 @@ - (void)createStripeTokenWithPayment:(PKPayment *)payment completion:(void (^)(N
             completion(token.tokenId, nil);
         }
     }];
-#endif
 }
 
 // Braintree
```

**Comment by nabilfreeman** [comment]
Hi all, yes this is to do with a newer version of Stripe SDK no longer supporting Objective-C headers. The options are to refactor the library to work with the new version or pin Stripe SDK to version 19 which I will do in the short term to get the library working again.
